---
- name: Infra | Provision Infra Terraform
  hosts: all

  tasks:

    - name: create x template
      template: 
        src: "{{ item }}"
        dest: ../../terraform-live/service1/{{ item | basename | regex_replace('.j2','') }}
      with_fileglob:
        - ../../terraform-live/service1/templates/*.j2
      delegate_to: localhost

    - name: Deploy Infra | Terraform Destroy
      terraform:
        project_path: "../../terraform-live/service1"
        state: absent
      delegate_to: localhost
      register: terraformoutputdestroy

    - name: Display OutPut
      debug: var=terraformoutputdestroy
