image:
  name: sarlindo/terraform-ansible-docker-image

before_script:
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile default
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default
  - aws configure set region $AWS_REGION --profile default
  - aws configure set format text --profile default
  - terraform --version
  - ansible --version

stages:
  - plan
  - deploy

plan:
  stage: plan
  script:
    - pushd .
    - cd ansible/scripts
    - ./plan_service1.sh 
    - popd
  artifacts:
    name: plan
    paths:
      - $CI_PROJECT_DIR/terraform-live/service1/plan*
  only:
    - master  

deploy_staging:
  stage: deploy
  script:
    - pushd .
    - cd ansible/scripts
    - ./deploy_service1.sh
    - popd
  dependencies:
    - plan
  when: on_success
  environment:
    name: staging
  only:
    - master
