---
- name: Infra | Provision Infra Terraform
  hosts: all

  tasks:

    - name: Deploy Infra | Process Terraform J2 Templates
      template: 
        src: "{{ item }}"
        dest: ../../terraform-live/global/aws-vpc-networking/{{ item | basename | regex_replace('.j2','') }}
      with_fileglob:
        - ../../terraform-live/global/aws-vpc-networking/*.j2
      delegate_to: localhost

    - name: Deploy Infra | Terraform Apply
      terraform:
        project_path: "../../terraform-live/global/aws-vpc-networking"
        plan_file: "./plan.out"
        force_init: True
        state: present
      delegate_to: localhost
      register: terraformoutputapply

    - name: Deploy Infra | Debug Diff
      debug: var=terraformoutputapply.stdout_lines
