---
- name: Infra | Provision Infra Terraform
  hosts: all

  tasks:

    - name: create x template
      template: 
        src: "{{ item }}"
        dest: ../../terraform-live/stage/us-east-1/service1/{{ item | basename | regex_replace('.j2','') }}
      with_fileglob:
        - ../../terraform-live/stage/us-east-1/service1/*.j2
      delegate_to: localhost

    - name: Deploy Infra | Terraform Destroy
      terraform:
        project_path: "../../terraform-live/stage/us-east-1/service1"
        plan_file: "/tmp/a.out"
        force_init: True
        variables_file:
          - "../../stage.tfvars"
        state: absent
      delegate_to: localhost
      register: terraformoutputdestroy

    - name: Display OutPut
      debug: var=terraformoutputdestroy
