---
- name: Infra | Provision Infra Terraform
  hosts: all

  tasks:

    - name: Deploy Infra | Process Terraform J2 Templates
      template: 
        src: "{{ item }}"
        dest: ../../terraform-live/global/aws-vpc-networking/{{ item | basename | regex_replace('.j2','') }}
      with_fileglob:
        - ../../terraform-live/global/aws-vpc-networking/*.j2
      delegate_to: localhost

    - name: Deploy Infra | Terraform Destroy
      terraform:
        project_path: "../../terraform-live/global/aws-vpc-networking"
        state: absent
      delegate_to: localhost
      register: terraformoutputdestroy

    - name: Deploy Infra | Debug Diff
      debug: var=terraformoutputdestroy.stdout_lines
