---
- name: test
  hosts: localhost

  vars:
   ans_tf_services:
     - name: "service1"
       terraform_projectpath: "../../terraform-live/service1"
       terraform_planname: "../../terraform-live/service1/service1_plan.out"
       destroy: false
       aws_accounts:
         - account: "1234"
           aws_regions:
             - "us-east1"
             - "ca-central-1"
         - account: "5436"
           aws_regions:
             - "us-east-1"
         - account: "4444"
           aws_regions:
             - "us-east-1"
 
     - name: "service2"
       terraform_projectpath: "../../terraform-live/service2"
       terraform_planname: "../../terraform-live/service1/service2_plan.out"
       destroy: false
       aws_accounts:
         - account: "1234"
           aws_regions:
             - "us-east1"
             - "ca-central-1"
         - account: "5436"
           aws_regions:
             - "us-east-1"
  tasks:

    - name: test
      debug: msg="{{item.0.name}},{{item.0.terraform_planname}},{{ item.1.account}},{% for region in item.1.aws_regions %}{{ region }} {% endfor %}"
      with_subelements:
        - "{{ ans_tf_services }}"
        - aws_accounts

    - set_fact:
        myvar: "{{ myvar|default([])|union([item.1]) }}"
      with_subelements:
        - "{{ ans_tf_services }}"
        - aws_accounts

    - debug:
        var: myvar
