- name: Deploy Infra | Process Templates
  template: 
    src: "{{ item }}"
    dest: "{{ ans_terraform_projectpath}}/{{item | basename | regex_replace('.j2','') }}"
  with_fileglob:
    - "{{ ans_terraform_projectpath }}/templates/*.j2"
  delegate_to: localhost

- name: Deploy Infra | Terraform Init
  command: terraform init
          -input=false
          {{ ans_terraform_projectpath }}
  register: result
  failed_when: result.rc != 0
  changed_when: "result.rc == 0"
  delegate_to: localhost

- name: Deploy Infra | Display Output
  debug: var=result

- name: Deploy Infra | Terraform Validate
  command: terraform validate 
          {{ ans_terraform_projectpath }}
  register: result
  failed_when: result.rc != 0
  changed_when: "result.rc == 0"
  delegate_to: localhost

- name: Deploy Infra | Display Output
  debug: var=result

- name: Deploy Infra | Terraform Build Destroy Plan
  command: terraform plan
        -detailed-exitcode
        -input=false
        -out="{{ ans_terraform_planname }}"
        -destroy
        {{ ans_terraform_projectpath }}
  register: result
  failed_when: result.rc == 1
  changed_when: "result.rc == 2"
  delegate_to: localhost
  when: ans_destroy

- name: Deploy Infra | Terraform Build Apply Plan
  command: terraform plan
        -detailed-exitcode
        -input=false
        -out="{{ ans_terraform_planname }}"
        {{ ans_terraform_projectpath }}
  register: result
  failed_when: result.rc == 1
  changed_when: "result.rc == 2"
  delegate_to: localhost
  when: not ans_destroy

- name: Deploy Infra | Display Output
  debug: var=result

- name: Deploy Infra | Terraform Apply
  command: terraform apply
        -auto-approve
        -input=false
        "{{ ans_terraform_planname }}"
  register: result
  failed_when: result.rc != 0
  changed_when: "result.rc == 0"
  delegate_to: localhost

- name: Deploy Infra | Display Output
  debug: var=result
