---
#--------------------------------------------------------------------
# global
#--------------------------------------------------------------------
ans_app_name: app1
ans_environment: stage
ans_aws_account: awsaccount1
ans_aws_tag_owner: "arlindo santos"
ans_aws_tag_environment: "{{ ans_environment }}"

#--------------------------------------------------------------------
# services
#--------------------------------------------------------------------
ans_tf_services:
  - name: "service1"
    # provider
    aws_provider_region: "us-east-1"
    aws_provider_profile: "ansiblepersonal"
    # state
    terraform_s3_state_bucket: "terraform-up-and-running-state.arlindo.ca"
    terraform_aws_state_key: "{{ ans_aws_account }}/service1/us-east-1/{{ ans_environment }}/terraform.tfstate"
    terraform_state_aws_region: "us-east-1"
    terraform_dynamodb_locktable_name: "terraform-locks"
    # tf project
    terraform_projectpath: "../../terraform-live/service1"
    terraform_planname: "../../terraform-live/service1/plan_service1.out"
    destroy: true
    # rds
    aws_rds_module_source: "terraform-aws-modules/rds/aws"
    aws_rds_module_version: "1.15.0"
    aws_rds_engine: "mysql"
    aws_rds_engine_version: "5.7.19"
    aws_rds_instance_class: "db.t2.large"
    aws_rds_allocated_storage: 5
    aws_rds_storage_encrypted: false
    aws_rds_dbport: 3306
    aws_rds_dbparmgroup: "mysql5.7"
    aws_rds_dbuser: "dbuser1"
    aws_rds_dbpassword: "YourPwdShouldBeLongAndSecure!"
    aws_rds_maintenance_window: "Mon:00:00-Mon:03:00"
    aws_rds_backup_window: "03:00-06:00"
    aws_rds_backup_retention_period: 0
    # sg
    aws_sg_module_source: "terraform-aws-modules/security-group/aws"
    aws_sg_module_version: "1.22.0"
    aws_sg_security_groups:
       - name: "{{ ans_environment}}-{{ ans_app_name }}-ssh-SG"
         modulename: "security-group-ssh"
         desc: "This sg is for ssh access"
         ingress_with_cidr_rules:
           - rule: "ssh-tcp"
             cidr_blocks: "0.0.0.0/0"
       - name: "{{ ans_environment}}-{{ ans_app_name }}-mysql-SG"
         modulename: "security-group-mysql"
         desc: "This sg is for mysql"
         ingress_with_cidr_rules:
           - rule: "mysql-tcp"
             cidr_blocks: "0.0.0.0/0"
       - name: "{{ ans_environment}}-{{ ans_app_name }}-elb-SG"
         modulename: "security-group-elb"
         desc: "This sg is for elb"
         ingress_with_cidr_rules:
           - rule: "http-80-tcp"
             cidr_blocks: "0.0.0.0/0"
       - name: "{{ ans_environment}}-{{ ans_app_name }}-app-SG"
         modulename: "security-group-app"
         desc: "This sg is for app"
         ingress_with_cidr_rules:
           - rule: "http-80-tcp"
             cidr_blocks: "0.0.0.0/0"

    # elb
    aws_elb_module_source: "terraform-aws-modules/elb/aws"
    aws_elb_module_version: "1.2.0"
    aws_elb_internal: false
    aws_elb_listeners:
      - instance_port: "80"
        instance_protocol: "HTTP"
        lb_port: "80"
        lb_protocol: "HTTP"
    aws_elb_health_checks:
      - target: "HTTP:80/"
        interval: 30
        healthy_threshold: 2
        unhealthy_threshold: 2
        timeout: 5
    # bastion ec2
    aws_ec2_bastion_module_source: "terraform-aws-modules/ec2-instance/aws"
    aws_ec2_bastion_module_version: "1.5.0"
    aws_ec2_bastion_associate_public_ip_address: true
    aws_ec2_bastion_key_name: "ansible"
    aws_ec2_bastion_instance_type: "t2.micro"
    # asg
    aws_asg_module_source: "terraform-aws-modules/autoscaling/aws"
    aws_asg_module_version: "2.3.0"
    aws_asg_key_name: "ansible"
    aws_asg_instance_type: "t2.micro"
    aws_asg_min_size: 0
    aws_asg_max_size: 1
    aws_asg_desired_capacity: 1
    aws_asg_wait_for_capacity_timeout: 0
    aws_asg_associate_public_ip_address: false
    aws_asg_ebs_block_device_name: "/dev/xvdz"
    aws_asg_ebs_block_volume_type: "gp2"
    aws_asg_ebs_block_delete_on_termination: true
    aws_asg_ebs_block_volume_size: 20
    aws_asg_ebs_root_device_name: "/dev/xvdz"
    aws_asg_ebs_root_volume_type: "gp2"
    aws_asg_ebs_root_delete_on_termination: true
    aws_asg_ebs_root_volume_size: 20
    # vpc
    aws_vpc_module_source: "terraform-aws-modules/vpc/aws"
    aws_vpc_module_version: "1.30.0"
    aws_vpc_name: "vpc-{{ ans_environment }}"
    aws_vpc_cidr: "10.10.0.0/16"
    aws_vpc_azs: '"us-east-1a", "us-east-1b"'
    aws_vpc_private_subnets: '"10.10.1.0/24", "10.10.2.0/24"'
    aws_vpc_public_subnets: '"10.10.11.0/24", "10.10.12.0/24"'
    aws_vpc_create_database_subnet_group: false
    aws_vpc_enable_nat_gateway: true
    aws_vpc_enable_vpn_gateway: false
    aws_vpc_enable_s3_endpoint: true
    aws_vpc_enable_dynamodb_endpoint: true
    aws_vpc_enable_dhcp_options: false

  - name: "service2"
    # provider
    aws_provider_region: "ca-central-1"
    aws_provider_profile: "ansiblepersonal"
    # state
    terraform_s3_state_bucket: "terraform-up-and-running-state.arlindo.ca"
    terraform_aws_state_key: "{{ ans_aws_account }}/service2/ca-central-1/{{ ans_environment }}/terraform.tfstate"
    terraform_state_aws_region: "us-east-1"
    terraform_dynamodb_locktable_name: "terraform-locks"
    # tf project
    terraform_projectpath: "../../terraform-live/service2"
    terraform_planname: "../../terraform-live/service2/plan_service2.out"
    destroy: true
    # vpc
    aws_vpc_module_source: "terraform-aws-modules/vpc/aws"
    aws_vpc_module_version: "1.30.0"
    aws_vpc_name: "vpc-{{ ans_environment }}"
    aws_vpc_cidr: "10.10.0.0/16"
    aws_vpc_azs: '"ca-central-1a", "ca-central-1b"'
    aws_vpc_private_subnets: '"10.10.3.0/24", "10.10.4.0/24"'
    aws_vpc_public_subnets: '"10.10.13.0/24", "10.10.14.0/24"'
    aws_vpc_create_database_subnet_group: false
    aws_vpc_enable_nat_gateway: true
    aws_vpc_enable_vpn_gateway: false
    aws_vpc_enable_s3_endpoint: true
    aws_vpc_enable_dynamodb_endpoint: true
    aws_vpc_enable_dhcp_options: false
